// Reference-only values preserve the XML's visible inconsistencies. Never feed them into IPC.
export const previewTokens = [
  {
    id: 'preview-jup',
    ticker: 'JUP',
    name: 'Jupiter',
    balance: '128.45',
    sol: '0.0183',
    usd: '$3.04',
    art: 'jup',
    selected: true,
  },
  {
    id: 'preview-bonk',
    ticker: 'BONK',
    name: 'Bonk',
    balance: '5,420,000',
    sol: '0.0061',
    usd: '$1.02',
    art: 'bonk',
    selected: true,
  },
  {
    id: 'preview-wif',
    ticker: 'WIF',
    name: 'dogwifhat',
    balance: '12,340',
    sol: '0.0029',
    usd: '$0.48',
    art: 'wif',
    selected: true,
  },
  {
    id: 'preview-ray',
    ticker: 'RAY',
    name: 'Raydium',
    balance: '240.12',
    sol: '0.0018',
    usd: '$0.29',
    art: 'ray',
    selected: true,
  },
  {
    id: 'preview-pyth',
    ticker: 'PYTH',
    name: 'Pyth Network',
    balance: '1,250',
    sol: '0.0012',
    usd: '$0.20',
    art: 'pyth',
    selected: true,
  },
  {
    id: 'preview-samo',
    ticker: 'SAMO',
    name: 'Samoyedcoin',
    balance: '890,000',
    sol: '0.0004',
    usd: '$0.07',
    art: 'samo',
    selected: false,
  },
  {
    id: 'preview-orca',
    ticker: 'ORCA',
    name: 'Orca',
    balance: '45.2',
    sol: '0.0003',
    usd: '$0.05',
    art: 'orca',
    selected: false,
  },
];

export const previewDeadTokens = [
  ['SCAMINU', 'Scam Inu', '420,000,000'],
  ['RUGCAT', 'RugCat', '133,700,000'],
  ['MOONRUG', 'MoonRug', '999,000'],
  ['FAKEAI', 'Fake AI', '2,500,000'],
  ['ELON2.0', 'Elon 2.0', '1,000,000'],
  ['TRUSTME', 'Trust Me Bro', '777,777'],
  ['SAFEEUR', 'Safe EUR', '888,000'],
] as const;

export const scanSteps = [
  'DOCKING WALLET…',
  'SCANNING CARGO HOLD…',
  'ANALYZING TOKENS…',
  'CHECKING JUPITER ROUTES…',
  'INSPECTING ACCOUNTS…',
  'GENERATING MANIFEST…',
];
export const salvageSteps = [
  'Swapping JUP → SOL',
  'Swapping BONK → SOL',
  'Swapping WIF → SOL',
  'Empty account closed',
  'DEAD TOKEN — burning…',
  'Closing empty account…',
  'Swapping RAY → SOL',
  'Swapping PYTH → SOL',
  'Finalizing transactions…',
];
