[package]
name = "dock-flints-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
mpl-token-metadata.workspace = true
solana-account-decoder.workspace = true
solana-rpc-client.workspace = true
solana-rpc-client-api.workspace = true
solana-commitment-config.workspace = true
solana-pubkey.workspace = true
solana-pubkey-v2.workspace = true
spl-token-2022-interface.workspace = true
spl-token-interface.workspace = true
tokio.workspace = true
mpl-core.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
solana-account.workspace = true
solana-keypair.workspace = true
solana-signer.workspace = true
solana-transaction.workspace = true
solana-message.workspace = true
solana-instruction.workspace = true
solana-hash.workspace = true
bincode.workspace = true
thiserror.workspace = true
base64.workspace = true

[dev-dependencies]
async-trait.workspace = true
borsh.workspace = true
